remote_theme: dracula/gh-pages
plugins:
  - jekyll-remote-theme

show_downloads: true
show_header: true

github:
  owner_name: Griffin
  owner_url: https://github.com/dsgriffin
  repository_url: https://github.com/nft-origins/nft-origins.github.io

title: NFT Origins
description: All about early blockchain collectibles
icon: /favicon.ico
